name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build depends
      run: "apt-get update; apt-get install -y libedit-dev"
    - name: make
      run: "cd src; make"
    - name: test
      run: "cd src; ./kerf_test"
